### ISSUE TITLE
why wrong result!

### ISSUE THREAD

**Issue by yuandm** [AbangLZU/multi_lidar_calibration#1]
I can not get right result.    Is there some things I should take into account?

**Comment by sifeng666** [comment]
I think this kind of single-frame lidars calibration is not good enough, you should consider other calibration methods. I'm writing a version of map-optimization lidars calibration method, but not finished yet. 😄

**Comment by AbangLZU** [comment]
Try the new version.
If you want more details, read my blog in csdn.
